### ISSUE TITLE
Error: name 'username' is not defined

### ISSUE THREAD

**Issue by CamilleHbp** [alallier/Mattermost-Export#7]
When running the script with the flags `python ./MMExport2PDF.py -t {teamName} -a {adminToken} -u {userName} -s {myInstance}.cloud.mattermost.com`, I get the following error: `name 'username' is not defined`

The user is valid though. If I change the user to an invalid one, I get another error `Failed to get user ID for: invalid_user`.

I tried checking in the script but it is one big file and not easy to navigate ^^

I would appreciate the help and support. And also, thank you very much for your script!

**Comment by alallier** [comment]
You could be encountering what is described in #5. Can you do some debugging around this [line](https://github.com/alallier/Mattermost-Export/blob/74639de8753fff7dfefd4530b342046c2e7494bb/MMExport2PDF.py#L530) to confirm.

It is not enough to just have _your_ user resolve on the API, it must resolve everyone you have ever chatted with. Fixing #5 with a non-crashing error would keep things happier, just haven't had time to do it yet. Also, happy to take a PR!

**Comment by CamilleHbp** [comment]
I'm sorry but I can't. Mattermost has deleted all my cloud data before I could export them. I guess I will never use the project again, it lacks an easy way out. I'm closing this since my data does not exist anymore.
